service: my-graphql-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  getMembers:
    handler: handler.getMembers
    events:
      - http:
          path: /slasscom
          method: post
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000 # Use port 4000 for the API Gateway
    lambdaPort: 4002 # Use port 4002 for the Lambda function
